-- Basic schema for BarkBuddy MVP
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR(64) NOT NULL,
    breed VARCHAR(64) NOT NULL,
    age INT DEFAULT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS ACTIVITIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dog_id INT NOT NULL,
    user_id INT NOT NULL,
    type VARCHAR(32) NOT NULL,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dog_id) REFERENCES DOGS(id),
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);
